### PR TITLE
Add Ubuntu support

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Add Ubuntu support.

### CODE REVIEW

**Comment by scrat14** [comment]
Thanks for the pull request.
Please give me a few days to verify the changes.

**Comment by nvtkaszpir** [comment]
any progress on this, @scrat14 ?

**Comment by scrat14** [comment]
Sorry, I was really busy last weeks.
Can you please send resend me the pull request in a way that I can merge it (at the moment there's a merge conflict with manifests/init.pp). Thanks a lot!

Btw, there's a typo in commit 6713e0b253748950285b09666ec76314905305a8 - README.md line 77 - it should be named Ubuntu 16.04 instead of 14.04.

**Comment by nvtkaszpir** [comment]
Fixed typo. Will see merge conflict.

**Comment by scrat14** [comment]
Thanks a lot!

**Pull request merged**
